### ISSUE TITLE
Unable to start EVoMaster in public petstore API

### ISSUE THREAD

**Issue by msbasanth** [WebFuzzing/EvoMaster#1055]
Hi,

**Commandline used**
evomaster --blackBox true --bbSwaggerUrl https://petstore3.swagger.io/api/v3/openapi.json  --outputFormat JAVA_JUNIT_4 --maxTime 30s --ratePerMinute 60

**Commandline logs:**
* EvoMaster version: 3.0.0
* Loading configuration file from: C:\Program Files\evomaster\em.yaml
* ←[31mWARNING: You are doing Black-Box testing, but you did not specify the 'problemType'. The system will default to RESTful API testing.←[0m
* Initializing...
21:04:32.683 [main] WARN  o.t.u.TestcontainersConfiguration - Attempted to read Testcontainers configuration file at file:/C:/Users/XXXXX/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: C:\Users\XXXX\.testcontainers.properties (The system cannot find the file specified)
21:04:35.979 [main] WARN  o.e.c.problem.rest.param.BodyParam - Not supported data type: application/octet-stream
* There are 19 usable RESTful API endpoints defined in the schema configuration
21:04:36.044 [main] WARN  o.e.c.s.gene.optional.ChoiceGene - cannot bind ChoiceGene with StringGene
* Starting to generate test cases
* ←[31m[ERROR] ←[0m←[33mERROR related to the system under test: Invalid URL: /api/v3
  For white-box testing, look at the logs of the EvoMaster Driver to help debugging this problem.←[0m

openjdk version "1.8.0_412"
OpenJDK Runtime Environment (Zulu 8.78.0.19-CA-win64) (build 1.8.0_412-b08)
OpenJDK 64-Bit Server VM (Zulu 8.78.0.19-CA-win64) (build 25.412-b08, mixed mode)

Node Version: v18.17.0
.Net: 8.0.201

Not sure what I am missing in command line error "Invalid URL: /api/v3" . But we could see that https://petstore3.swagger.io/api/v3/openapi.json is a valid URL

Thanks
Basanth

**Comment by arcuri82** [comment]
hi @msbasanth ,

 thanks for reporting this bug. A workaround is to add:

` --bbTargetUrl https://petstore3.swagger.io`

which works (I tested it locally).

The "bug" is in the handling of the `server` entry in the schema. 
OpenAPI specs "wrongly" defines it as a URL, whereas in fact in the specs it is treated as a URI (confusing!).
EvoMaster currently handles it as URL, which fails like in this case when dealing with a URI that is not a URL.

**Comment by msbasanth** [comment]
@arcuri82 Thanks for the quick reply. After including _--bbTargetUrl_  I could see the test cases are getting generated fine.

**Comment by arcuri82** [comment]
Dear @msbasanth ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
