### ISSUE TITLE
Details how to use evomaster + info on found faults

### ISSUE THREAD

**Issue by bungdanar** [WebFuzzing/EvoMaster#765]
Hi, I'm currently trying evomaster to do blackbox testing on a RESTful API written in the NodeJs and Python programming languages. I'm using evomaster via windows installer.

I've tried running evomaster for 15 minutes and managed to generate tests. After the tests have been generated, should I run the tests? And how do I install dependencies to be able to run the tests?

**Comment by arcuri82** [comment]
hi.
  by default, tests are generated in Java for JUnit. If you using NodeJS, can try the experimental option `--outputFormat=JS_JEST`

**Comment by bungdanar** [comment]
Hi, thank you so much for the answer. I was finally able to run the JUnit tests after installing the required dependencies although it was quite difficult as I don't have much experience in the Java ecosystem.

I actually will use evomaster for my thesis paper. How do we know how many bugs the evomaster has found? For example, if there are 2 tests in the EvoMaster_faults_Test.java file, does that mean that evomaster has found 2 bugs?

**Comment by arcuri82** [comment]
hi.
  on the console, you get the info `Potential faults: ...`. But, indeed, we should provide better information in the generated `EvoMaster_faults_Test` files

**Comment by arcuri82** [comment]
you can also use `--writeStatistics=true`, and check the `potentialFaults` column there in the generated CSV file

**Comment by bungdanar** [comment]
There is no information about Potential Faults in the console output. Maybe I missed a certain option parameter.

![em-consolo-output](https://github.com/EMResearch/EvoMaster/assets/37931098/d5809ac4-d98a-48f4-95f2-e4e17d4b825e)

But the information about Potential Faults exists in the statistics.csv file

![em-statistic-output](https://github.com/EMResearch/EvoMaster/assets/37931098/cc214a5e-fe35-4887-8525-35119775bd06)

Anyway, thank you very much for the response.

**Comment by arcuri82** [comment]
it is a bug, as it looks like we print it only for White-Box testing, but not for Black-box

**Comment by wanglewang** [comment]
> --writeStatistics=true

if a api need auth token,how add token to testcases

**Comment by alegonzalezz** [comment]
@wanglewang I have the same problem. Can did You fix it?

**Comment by arcuri82** [comment]
closed as now found faults are explicitly added as comments in the generated tests
