### ISSUE TITLE
Is it normal that EvoMaster combined "sucess" and "other" tests into "fault_representatives"?

### ISSUE THREAD

**Issue by aruvic** [WebFuzzing/EvoMaster#988]
Hi,

Is it normal that EvoMaster combined "success" and "other" tests into "fault_representatives"?

After running for 14 hours EvoMaster finished with following stats 
```
* Recomputing full coverage for 39 tests
* Going to save 32 tests to 
* Potential faults: 6
* Bytecode line coverage: 54% (213 out of 393 in 14 units/classes)
* Successfully executed (HTTP code 2xx) 7 endpoints out of 7 (100%)
```

It generated

- 16 tests in EvoMaster_successes_Test.java
and
- 16 tests in EvoMaster_others_Test.java

and combined all tests (32) into **EvoMaster_fault_representatives_Test.java**

Is my understanding correct that:
- EvoMaster_successes_Test are sunny day scenarios
- EvoMaster_others_Test are failures which are gracefully handled by the REST API
- and EvoMaster_fault_representatives_Test should be the potential faults

Where and how can I find the "Potential faults: 6"? if EvoMaster_fault_representatives_Test contains 32 tests?

Please find attached also the statistics.csv and the tests generated:
[statistics.csv](https://github.com/EMResearch/EvoMaster/files/15429378/statistics.csv)
[test_output.zip](https://github.com/EMResearch/EvoMaster/files/15429386/test_output.zip)

Br,
Alen

**Comment by arcuri82** [comment]
hi @aruvic 
  this issue should now had been resolved in the `master` branch

**Comment by aruvic** [comment]
> hi @aruvic this issue should now had been resolved in the `master` branch

thanks, I will use and test it
